config/routes.rb
Bookert::Application.routes.draw do
  resources :bookings

  get 'stream(/:items)' => 'bookings#stream', :as => :bookings_stream
  
  get 'bookings/date/:booking_date' => 'bookings#on_date', :as => :bookings_on_date

end

app/models/booking.rb
#
# Basic model representing a hotel booking
# #boston, #pemaquid
#
class Booking
  include Mongoid::Document
  
  DOUBLE="DB"
  SINGLE="SG"
  QUEEN="QN"  
  KING="KG"
  EXECUTIVE="EX"
  JUNIOR="JN"

  
  field :booking_id, :type => String
  field :nights, :type => Integer
  field :rooms, :type => Integer
  field :booking_date, :type => String
  field :room_type, :type => String
  field :price, :type => Integer
  
  validates_format_of :booking_date, :with => /^[0-9]{4}[-][0-9]{2}[-][0-9]{2}$/
  validates :nights, :numericality => { :greater_than_or_equal_to => 0 }
  
  #
  # Return all bookings on this date
  #
  def self.on_date(book_date=nil)
    results = []
    results = Booking.where(booking_date: book_date) unless book_date.nil?
    results 
  end
  
end

app/models/fakey.rb
class Fakey
  
  def self.string(chars=10)
    (0...chars).map{('a' ... 'z').to_a[rand(26)] }.join
  end
  
  def self.number(max=10)
    (rand*max).to_i
  end
  
  def self.iso_date_long(days_out=365)
    d = (rand*days_out).to_i
    (Time.now + d.days).to_s
  end  
  
  def self.iso_date_short(days_out=365)
    Fakey.iso_date_long.slice(0,10)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  # make doubles most likely
  ROOM_TYPES = [Booking::DOUBLE,Booking::DOUBLE,Booking::SINGLE,Booking::DOUBLE,Booking::QUEEN,Booking::QUEEN,Booking::KING,Booking::EXECUTIVE,Booking::EXECUTIVE,Booking::SINGLE,Booking::SINGLE,Booking::DOUBLE,Booking::DOUBLE,Booking::JUNIOR]
  
  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookings }
    end
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @booking = Booking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/new
  # GET /bookings/new.json
  def new
    @booking = Booking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/1/edit
  def edit
    @booking = Booking.find(params[:id])
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(params[:booking])

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render json: @booking, status: :created, location: @booking }
      else
        format.html { render action: "new" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookings/1
  # PUT /bookings/1.json
  def update
    @booking = Booking.find(params[:id])

    respond_to do |format|
      if @booking.update_attributes(params[:booking])
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url }
      format.json { head :no_content }
    end
  end

  #
  # GET /stream/10000
  # GET /stream/10000.json
  #
  def stream
    
    stream_count = (params[:items] || 1000).to_i 
    
    start = Time.now
    added = 0
    
    stream_count.times do
      b = Booking.new(
        :booking_id => Fakey.string, 
        :nights => Fakey.number(4), 
        :rooms => Fakey.number(1)+1, 
        :booking_date => Fakey.iso_date_short(50), 
        :room_type => ROOM_TYPES[Fakey.number(ROOM_TYPES.length)],
        :price => 100+Fakey.number(76))
      
      added += 1 if b.save
      
    end
    
    elapsed = (Time.now - start).to_i
    
    respond_to do |format|
      format.html { redirect_to :bookings, notice: "#{added} bookings successfully created in #{elapsed}s." }
      format.json { render json: "#{added} bookings successfully created in #{elapsed}s.", status: :created}
    end    
    
  end


  #
  # GET /bookings/date/2013-07-24
  # GET /bookings/date/2013-07-24.json
  #
  def on_date
    @bookings = []
    @bookings = Booking.on_date(params[:booking_date]) if params[:booking_date]
    
    respond_to do |format|
      format.html {render "index"}
      format.json {render json: @bookings}
    end
    
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identifier %><br />
    <%= f.text_field :booking_id %>
  </div>
  <div class="field">
    <%= f.label :nights %><br />
    <%= f.number_field :nights %>
  </div>
  <div class="field">
    <%= f.label :rooms %><br />
    <%= f.number_field :rooms %>
  </div>
  <div class="field">
    <%= f.label :booking_date %><br />
    <%= f.text_field :booking_date %>
  </div>

  <div class="field">
    <%= f.label :room_type %><br />
    <%= f.text_field :room_type %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <tr>
    <th>Booking Id</th>
    <th>Nights</th>
    <th>Rooms</th>
    <th>Date</th>
    <th>Room type</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bookings.each do |booking| %>
  <tr>
    <td><%= booking.booking_id %></td>
    <td><%= booking.nights %></td>
    <td><%= booking.rooms %></td>
    <td><%= booking.booking_date %></td>
    <td><%= booking.room_type %></td>
    <td><%= booking.price %></td>
    <td><%= link_to 'Show', booking %></td>
    <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
    <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Identifier:</b>
  <%= @booking.booking_id %>
</p>

<p>
  <b>Nights:</b>
  <%= @booking.nights %>
</p>

<p>
  <b>Rooms:</b>
  <%= @booking.rooms %>
</p>

<p>
  <b>Date:</b>
  <%= @booking.booking_date %>
</p>

<p>
  <b>Room type:</b>
  <%= @booking.room_type %>
</p>

<p>
  <b>Price:</b>
  <%= @booking.price %>
</p>


<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookert</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>